version: '2'

services:
  # MONGODB
  mongo:
    image: mongo:4.2.0
    hostname: mongo.myrepl
    ports:
      - "127.0.0.1:27017:27017"
    expose:
      - "27017"
    networks:
      default:
         aliases:
            - mongo.myrepl
    command:
    - --storageEngine
    - wiredTiger
    - --replSet
    - myrepl
    depends_on:
      - mongo-2
      - mongo-3

  # MONGODB-2
  mongo-2:
    image: mongo:4.2.0
    hostname: mongo-2.myrepl
    ports:
      - "127.0.0.2:27017:27017"
    expose:
      - "27017"
    networks:
      default:
         aliases:
            - mongo-2.myrepl  
    command:
    - --storageEngine
    - wiredTiger
    - --replSet
    - myrepl
  # MONGODB-3
  mongo-3:
    image: mongo:4.2.0
    hostname: mongo-3.myrepl
    ports:
      - "127.0.0.3:27017:27017"
    expose:
      - "27017"
    networks:
      default:
         aliases:
            - mongo-3.myrepl
    command:
    - --storageEngine
    - wiredTiger
    - --replSet
    - myrepl
